# Generated by Django 3.1.1 on 2020-09-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_ttn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Autorisation', models.CharField(choices=[('Accés autorisé', 'Accés autorisé'), ('Accés non autorisé', 'Accés non autorisé')], max_length=50)),
                ('Porte', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('Zone', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=10)),
            ],
        ),
    ]
