# Generated by Django 3.1.1 on 2021-06-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ttn', '0003_data_ttn_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_ttn',
            name='matricule_id',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data_ttn',
            name='status',
            field=models.CharField(choices=[('Employé(e)', 'Employé(e)'), ('Visiteur', 'Visiteur')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
