# Generated by Django 3.1.1 on 2021-06-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ttn', '0004_auto_20210608_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_ttn',
            name='id',
        ),
        migrations.AlterField(
            model_name='data_ttn',
            name='badge',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
