# Generated by Django 3.1.1 on 2021-06-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ttn', '0005_auto_20210615_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_ttn',
            name='Nom',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
